//What is error

//What happened when error occurs and the reason(abnormal termination)

try{
//let a=10;
console.log(a)
}catch(error){
    console.log(error)
}

console.log("hello")
console.log("good evening")
function test(){
    return "test called"
}
test()


//Handle error
